### ISSUE TITLE
Build failed with version 1.5.4

### ISSUE THREAD

**Issue by davidefavia** [EddyVerbruggen/cordova-plugin-safariviewcontroller#114]
Hi,
I built a Cordova project for Android platform yesterday using plugin version `1.5.3`: everything worked fine. This morning build process fails, the only difference is the new version of this plugin used, today I'm using `1.5.4` (released yesterday).

```
* What went wrong:
A problem occurred configuring root project 'android'.
> Jack is required to support java 8 language features.  Either enable Jack or remove sourceCompatibility JavaVersion.VERSION_1_8.
```

I think the issue is with the new version, due to your comment inside the release notes: `Removed Jackass` [v1.5.4](https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller/releases/tag/1.5.4).

## System info (by Ionic)

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    Cordova Platforms : android 6.3.0
    Ionic Framework   : ionic1 ^1.3.5

System:

    ios-deploy : 1.8.6 
    ios-sim    : 5.0.8 
    Node       : v9.8.0
    npm        : 5.8.0 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.3 Build version 9E145 

Environment Variables:

    ANDROID_HOME : /Applications/Android Studio.app/sdk

Misc:

    backend : pro
```

Let me know if you need more info to understand the issue.
Thanks.

**Comment by EddyVerbruggen** [comment]
Just pin to an older version of the plugin for now.

See #108.

**Comment by davidefavia** [comment]
Thanks, I've already done it and it obviously works.

**Comment by matteobortolazzo** [comment]
Hi, I have the same error.
Plugin 1.5.3 and tools <= 27.
Am I missing something?

![sdk](https://user-images.githubusercontent.com/15217470/43320821-27594cbc-91aa-11e8-9ac2-b72231be6e51.PNG)

**Comment by WuglyakBolgoink** [comment]
Hallo @matteobortolazzo 

1) check exactly, that you have v1.5.3... if in config stay @~1.5.3" cordova install "v1.5.4"
2) if 1. is ok => remove cordova-android platform and install it again
3) if 1. and 2. doesn't help you => try to install "cordova-android-support-gradle-release"

**Comment by matteobortolazzo** [comment]
@WuglyakBolgoink I tried everything.
The latest error is this: 
![microsoftteams-image](https://user-images.githubusercontent.com/15217470/43322898-52f1d6cc-91b0-11e8-9411-2818fa5c75a5.png)

**Comment by WuglyakBolgoink** [comment]
@matteobortolazzo 

this is my list:
![image](https://user-images.githubusercontent.com/2271337/43323006-acb4e3ca-91b0-11e8-84ff-9baa151e049d.png)

try to upgrade your 

|Path|Version|Description|Location|
|---|---|---|---|
| platform-tools|  28.0.0  | Android SDK Platform-Tools|platform-tools/|

PS: Are u use cordova-android v7+?

**Comment by WuglyakBolgoink** [comment]
@matteobortolazzo 
also, I tested now on my project:

cordova-plugin-safariviewcontroller v1.5.3 was corectly compiled with:
+ cordova-android v6.3.0
+ cordova v6.5.0
+ cordova-ios v4.5.3
+ android build-tools v27.0.3
+ android platform-tools v28.0.0 

```html
    <plugin name="cordova-plugin-safariviewcontroller" spec="1.5.3" />
    <engine name="android" spec="6.3.0" />
    <engine name="ios" spec="4.5.3" />
    <plugin name="cordova-android-support-gradle-release" spec="^1.4.4">
        <variable name="ANDROID_SUPPORT_VERSION" value="23.+" />
    </plugin>
```

+ install all plugins
+ remove android platform and install again
+ do `cordova prepare`
+ do `cordova build android`

**Comment by matteobortolazzo** [comment]
Followed everything, same plugin, same cordova, same Android SDK, tested on 2 different PCs. Same 'transformJackWithJackForDebug' error :(

**Comment by WuglyakBolgoink** [comment]
@matteobortolazzo can u send us your config.xml?

**Comment by matteobortolazzo** [comment]
Here it is:
```xml
<?xml version='1.0' encoding='utf-8'?>
<widget id="aaa" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>AAA</name>
    <description>AAA</description>
    <author email="aaa" href="aaa">AAA</author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="aaa://*/*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <feature name="CDVWKWebViewEngine">
        <param name="ios-package" value="CDVWKWebViewEngine" />
    </feature>
    <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
    <preference name="ScrollEnabled" value="false" />
    <preference name="android-minSdkVersion" value="16" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreenDuration" value="300" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="3000" />
    <preference name="StatusBarOverlaysWebView" value="false" />
    <preference name="StatusBarBackgroundColor" value="#ffffff" />
    <preference name="SplashScreenDelay" value="3000" />
    <preference name="KeyboardResizeMode" value="ionic" />
    <preference name="orientation" value="portrait" />
    <platform name="android">
        <preference name="loadUrlTimeoutValue" value="70000" />
        <allow-intent href="market:*" />
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
        <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
        <splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png" />
        <splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />
        <splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png" />
        <splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png" />
        <splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png" />
        <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
        <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
        <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
        <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
        <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
        <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <icon height="57" src="resources/ios/icon/icon.png" width="57" />
        <icon height="114" src="resources/ios/icon/icon@2x.png" width="114" />
        <icon height="40" src="resources/ios/icon/icon-40.png" width="40" />
        <icon height="80" src="resources/ios/icon/icon-40@2x.png" width="80" />
        <icon height="120" src="resources/ios/icon/icon-40@3x.png" width="120" />
        <icon height="50" src="resources/ios/icon/icon-50.png" width="50" />
        <icon height="100" src="resources/ios/icon/icon-50@2x.png" width="100" />
        <icon height="60" src="resources/ios/icon/icon-60.png" width="60" />
        <icon height="120" src="resources/ios/icon/icon-60@2x.png" width="120" />
        <icon height="180" src="resources/ios/icon/icon-60@3x.png" width="180" />
        <icon height="72" src="resources/ios/icon/icon-72.png" width="72" />
        <icon height="144" src="resources/ios/icon/icon-72@2x.png" width="144" />
        <icon height="76" src="resources/ios/icon/icon-76.png" width="76" />
        <icon height="152" src="resources/ios/icon/icon-76@2x.png" width="152" />
        <icon height="167" src="resources/ios/icon/icon-83.5@2x.png" width="167" />
        <icon height="29" src="resources/ios/icon/icon-small.png" width="29" />
        <icon height="58" src="resources/ios/icon/icon-small@2x.png" width="58" />
        <icon height="87" src="resources/ios/icon/icon-small@3x.png" width="87" />
        <icon height="1024" src="resources/ios/icon/icon-1024.png" width="1024" />
        <splash height="1136" src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" />
        <splash height="1334" src="resources/ios/splash/Default-667h.png" width="750" />
        <splash height="2208" src="resources/ios/splash/Default-736h.png" width="1242" />
        <splash height="1242" src="resources/ios/splash/Default-Landscape-736h.png" width="2208" />
        <splash height="1536" src="resources/ios/splash/Default-Landscape@2x~ipad.png" width="2048" />
        <splash height="2048" src="resources/ios/splash/Default-Landscape@~ipadpro.png" width="2732" />
        <splash height="768" src="resources/ios/splash/Default-Landscape~ipad.png" width="1024" />
        <splash height="2048" src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536" />
        <splash height="2732" src="resources/ios/splash/Default-Portrait@~ipadpro.png" width="2048" />
        <splash height="1024" src="resources/ios/splash/Default-Portrait~ipad.png" width="768" />
        <splash height="960" src="resources/ios/splash/Default@2x~iphone.png" width="640" />
        <splash height="480" src="resources/ios/splash/Default~iphone.png" width="320" />
        <splash height="2732" src="resources/ios/splash/Default@2x~universal~anyany.png" width="2732" />
    </platform>
    <allow-navigation href="http://172.21.27.129:8100" />
    <allow-navigation href="http://172.16.24.111:8100" />
    <allow-navigation href="http://172.16.24.115:8101" />
    <plugin name="cordova-plugin-splashscreen" spec="^5.0.2" />
    <plugin name="cordova-plugin-file" spec="^6.0.1" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.3" />
    <plugin name="cordova-plugin-device" spec="^1.1.7" />
    <plugin name="com.synconset.imagepicker" spec="^2.1.10">
        <variable name="PHOTO_LIBRARY_USAGE_DESCRIPTION"/>
    </plugin>
    <plugin name="cordova-plugin-advanced-http" spec="^1.11.1" />
    <plugin name="cordova-plugin-network-information" spec="^2.0.1" />
    <plugin name="cordova-sqlite-storage" spec="^2.3.2" />
    <plugin name="cordova-plugin-crop" spec="^0.3.1" />
    <plugin name="cordova-plugin-ionic" spec="^4.1.7">
        <variable name="APP_ID" value="aaa" />
        <variable name="CHANNEL_NAME" value="Master" />
        <variable name="UPDATE_METHOD" value="auto" />
        <variable name="WARN_DEBUG" value="true" />
        <variable name="UPDATE_API" value="https://api.ionicjs.com" />
        <variable name="MAX_STORE" value="2" />
    </plugin>
    <plugin name="cordova-plugin-statusbar" spec="^2.4.2" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="^2.1.2" />
    <plugin name="cordova-plugin-camera" spec="^4.0.3" />
    <plugin name="cordova-plugin-filepath" spec="^1.3.0" />
    <plugin name="com-badrit-base64" spec="^0.2.0" />
    <plugin name="cordova-plugin-customurlscheme" spec="^4.3.0">
        <variable name="URL_SCHEME" value="aaa" />
        <variable name="ANDROID_SCHEME" value=" " />
        <variable name="ANDROID_HOST" value=" " />
        <variable name="ANDROID_PATHPREFIX" value="/" />
    </plugin>
    <plugin name="cordova-android-support-gradle-release" spec="^1.4.4">
        <variable name="ANDROID_SUPPORT_VERSION" value="23.+" />
    </plugin>
    <plugin name="cordova-plugin-safariviewcontroller" spec="^1.5.3" />
    <engine name="android" spec="~6.3.0" />
</widget>
```

**Comment by WuglyakBolgoink** [comment]
@matteobortolazzo 

As I wrote before, this line `<plugin name="cordova-plugin-safariviewcontroller" spec="^1.5.3" />` install v1.5.4 instead v1.5.3!!!

1) change config with this part: `spec="1.5.3"`
2) remove plugin and install again
3) optional +- reinstall platforms

**Comment by matteobortolazzo** [comment]
Sorry but every time I run 'ionic cordova run android' it changes the config.xml to '^1.5.3'.
However, I installed 1.5.3 manually with 'ionic cordova plugin add s..v..c@1.5.3' then add platform but the error doesn't change. I also checked 'android.json' into platforms/android and it's 1.5.3

**Comment by matteobortolazzo** [comment]
With my current setup 1.4.7 works fine. I'll stick with that.

**Comment by ish2028** [comment]
I am having the same problem but with both versions of 1.5.3 and 1.5.4.  Though it complies and runs fine for ios, just not android.

I am running
cordova-android: 6.3.0
cordova-android-support-gradle-release: 1.4.4, 23.+ (support version)

This is the error 
* What went wrong:
Execution failed for task ':transformClassesWithPreJackPackagedLibrariesForDebug'.

> java.lang.NullPointerException (no error message)

Any help please?

**Comment by mushishi78** [comment]
I had pinned to 1.5.3 in order to stop getting the error from 1.5.4. This worked at the time, but now I am also getting the the same error as @ish2028 :

```
Execution failed for task ':transformClassesWithPreJackPackagedLibrariesForDebug'.
> java.lang.NullPointerException (no error message)
```

Not having much googling for the error. Would also appreciate help.

**Comment by WuglyakBolgoink** [comment]
Hallo @mushishi78 
1) are u sure that you have a right version in your plugin folder?
2) remove plugins and platforms and install all again

show your cordova config.xml, if it possible.

**Comment by mushishi78** [comment]
Yeah I've got the correct version. It's a different error message for the different versions. I've removed all the plugins and platforms.

I've also manually edited the change in [#108](https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller/pull/108/files) and got the other error message. 

I also tried the using the engine and "cordova-android-support-gradle-release" from your comment above:

```
    <plugin name="cordova-plugin-safariviewcontroller" spec="1.5.3" />
    <engine name="android" spec="6.3.0" />
    <engine name="ios" spec="4.5.3" />
    <plugin name="cordova-android-support-gradle-release" spec="^1.4.4">
        <variable name="ANDROID_SUPPORT_VERSION" value="23.+" />
    </plugin>
```

My config.xml looks like this:

```
<?xml version='1.0' encoding='utf-8'?>
<widget
    id="REDACTED"
    version="1.1.21"
    versionCode="10021"
    versionName="Bridgewater"
    xmlns="http://www.w3.org/ns/widgets"
    xmlns:gap="http://phonegap.com/ns/1.0"
>
    <name>REDACTED</name>
    <description>REDACTED</description>
    <author email="REDACTED" href="REDACTED">REDACTED</author>
    <content src="index.html" />
    <icon src="res/icon/ios/icon-72@2x.png" />
    <preference name='phonegap-version' value='cli-7.1.0' />
    <preference name="FullScreen" value="false" />
    <preference name="webviewbounce" value="false" />
    <preference name="detect-data-types" value="true" />
    <preference name="exit-on-suspend" value="false" />
    <preference name="FadeSplashScreen" value="false" />
    <preference name="AutoHideSplashScreen" value="true" />
    <preference name="DisallowOverscroll" value="true" />
    <platform name="ios">
        <!-- APP_SECRET is for Microsoft App Center -->
        <preference name="APP_SECRET" value="REDACTED" />
        <preference name="iosPersistentFileLocation" value="Library" />
        <preference name="StatusBarOverlaysWebView" value="false" />
        <preference name="StatusBarBackgroundColor" value="#1d1d1d" />
        <preference name="StatusBarStyle" value="lightcontent" />
        <preference name="KeyboardDisplayRequiresUserAction" value="false" />
        <preference name="EnableViewportScale" value="true" />
        <preference name="CodePushDeploymentKey" value="REDACTED" />
        <icon height="180" src="res/icon/ios/icon-60@3x.png" width="180" />
        <icon height="60" src="res/icon/ios/icon-60.png" width="60" />
        <icon height="120" src="res/icon/ios/icon-60@2x.png" width="120" />
        <icon height="76" src="res/icon/ios/icon-76.png" width="76" />
        <icon height="152" src="res/icon/ios/icon-76@2x.png" width="152" />
        <icon height="40" src="res/icon/ios/icon-40.png" width="40" />
        <icon height="80" src="res/icon/ios/icon-40@2x.png" width="80" />
        <icon height="57" src="res/icon/ios/icon.png" width="57" />
        <icon height="114" src="res/icon/ios/icon@2x.png" width="114" />
        <icon height="72" src="res/icon/ios/icon-72.png" width="72" />
        <icon height="144" src="res/icon/ios/icon-72@2x.png" width="144" />
        <icon height="29" src="res/icon/ios/icon-small.png" width="29" />
        <icon height="58" src="res/icon/ios/icon-small@2x.png" width="58" />
        <icon height="50" src="res/icon/ios/icon-50.png" width="50" />
        <icon height="100" src="res/icon/ios/icon-50@2x.png" width="100" />
        <icon height="167" src="res/icon/ios/icon-83.5@2x.png" width="167" />
        <splash height="480" src="res/screen/ios/iphone-portrait.png" width="320" />
        <splash height="320" src="res/screen/ios/iphone-landscape.png" width="480" />
        <splash height="960" src="res/screen/ios/iphone-portrait-2x.png" width="640" />
        <splash height="640" src="res/screen/ios/iphone-landscape-2x.png" width="960" />
        <splash height="2208" src="res/screen/ios/iphone-portrait-2x.png" width="1242" />
        <splash height="1242" src="res/screen/ios/iphone-landscape-2x.png" width="2208" />
        <splash height="1024" src="res/screen/ios/ipad-portrait.png" width="768" />
        <splash height="768" src="res/screen/ios/ipad-landscape.png" width="1024" />
        <splash height="2048" src="res/screen/ios/ipad-portrait-2x.png" width="1536" />
        <splash height="1536" src="res/screen/ios/ipad-landscape-2x.png" width="2048" />
        <splash height="1136" src="res/screen/ios/iphone-portrait-568@2x.png" width="640" />
        <splash height="1334" src="res/screen/ios/iphone-portrait.png" width="750" />
    </platform>
    <platform name="android">
        <!-- APP_SECRET is for Microsoft App Center -->
        <preference name="APP_SECRET" value="REDACTED" />
        <preference name="android-targetSdkVersion" value="16" />
        <preference name="AndroidPersistentFileLocation" value="Compatibility" />
        <!--
            The singleTask launch mode is advised to be used with the custom URL schema:
            https://github.com/EddyVerbruggen/Custom-URL-scheme#android

            This is to avoid issues like:
            https://github.com/EddyVerbruggen/Custom-URL-scheme/issues/24
            https://github.com/EddyVerbruggen/Custom-URL-scheme/issues/160

            Basically without this, when logging in and redirecting back to the app,
            two instances of the app get opened side by side within the same activity.
            But what we want is the original app to be opened again.
        -->
        <preference name="AndroidLaunchMode" value="singleTask" />
        <gap:config-file parent="/manifest/application">
            android:windowSoftInputMode="adjustPan"
        </gap:config-file>
        <preference name="LoadUrlTimeoutValue" value="700000" />
        <preference name="android-build-tool" value="gradle" />
        <preference name="CodePushDeploymentKey" value="REDACTED" />
        <icon density="ldpi" src="res/icon/android/ldpi.png" />
        <icon density="mdpi" src="res/icon/android/mdpi.png" />
        <icon density="hdpi" src="res/icon/android/hdpi.png" />
        <icon density="xhdpi" src="res/icon/android/xhdpi.png" />
        <icon density="xxhdpi" src="res/icon/android/xxhdpi.png" />
        <icon density="xxxhdpi" src="res/icon/android/xxxhdpi.png" />
        <splash src="res/screen/android/splash-port-hdpi.png" />
        <splash density="port" src="res/screen/android/splash-port-hdpi.png" />
        <splash density="land" src="res/screen/android/splash-land-hdpi.png" />
        <splash density="land-ldpi" src="res/screen/android/splash-land-ldpi.png" />
        <splash density="land-mdpi" src="res/screen/android/splash-land-mdpi.png" />
        <splash density="land-hdpi" src="res/screen/android/splash-land-hdpi.png" />
        <splash density="land-xhdpi" src="res/screen/android/splash-land-xhdpi.png" />
        <splash density="port-ldpi" src="res/screen/android/splash-port-ldpi.png" />
        <splash density="port-mdpi" src="res/screen/android/splash-port-mdpi.png" />
        <splash density="port-hdpi" src="res/screen/android/splash-port-hdpi.png" />
        <splash density="port-xhdpi" src="res/screen/android/splash-port-xhdpi.png" />
    </platform>
    <platform name="windows">
        <splash height="300" src="res/screen/windows-phone/screen-portrait.jpg" width="620" />
    </platform>
    <feature name="Device">
        <param name="ios-package" value="CDVDevice" />
        <param name="android-package" value="org.apache.cordova.device.Device" />
    </feature>
    <feature name="File">
        <param name="ios-package" value="CDVFile" />
        <param name="android-package" value="org.apache.cordova.file.FileUtils" />
    </feature>
    <feature name="FileTransfer">
        <param name="ios-package" value="CDVFileTransfer" />
        <param name="android-package" value="org.apache.cordova.filetransfer.FileTransfer" />
    </feature>
    <access origin="*" />
    <allow-navigation href="https://REDACTED/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="http://*/*" />
    <engine name="ios" spec="4.5.4" />
    <engine name="android" spec="6.3.0" />
    <plugin name="cordova-plugin-camera" spec="~2.3.1">
        <variable name="CAMERA_USAGE_DESCRIPTION" value="REDACTED" />
        <variable name="PHOTOLIBRARY_USAGE_DESCRIPTION" value="REDACTED" />
    </plugin>
    <plugin name="cordova-plugin-device" spec="1.1.2" />
    <plugin name="cordova-plugin-geolocation" spec="2.4.3">
        <variable
            name="GEOLOCATION_USAGE_DESCRIPTION"
            value="REDACTED"
        />
    </plugin>
    <plugin name="cordova-plugin-inappbrowser" spec="1.3.0" />
    <plugin name="cordova-plugin-network-information" spec="1.2.0" />
    <plugin name="cordova-plugin-vibration" spec="2.1.0" />
    <plugin name="cordova-plugin-media" spec="2.2.0" />
    <plugin name="cordova-plugin-whitelist" spec="1.2.1" />
    <plugin name="cordova-plugin-screen-orientation" spec="v1.4.1" />
    <plugin name="cordova-plugin-splashscreen" spec="3.2.2" />
    <plugin name="cordova-plugin-statusbar" spec="2.1.3" />
    <plugin name="cordova-plugin-file-transfer" spec="1.6.3" />
    <plugin name="cordova-plugin-file" spec="4.2.0" />
    <plugin name="cordova-sqlite-storage" spec="0.8.5" />
    <plugin name="cordova-plugin-code-push" spec="1.11.0" />
    <plugin name="ionic-plugin-keyboard" spec="v2.2.0" />
    <plugin name="phonegap-plugin-barcodescanner" spec="5.0.0" />
    <plugin name="uk.co.workingedge.phonegap.plugin.launchnavigator" spec="3.1.1" />
    <plugin name="cordova-plugin-email" spec="1.1.1" />
    <plugin name="cordova-plugin-appavailability" spec="^0.4.2" />
    <plugin name="com.xmartlabs.cordova.market" spec="https://github.com/xmartlabs/cordova-plugin-market" />
    <plugin name="cordova-plugin-x-socialsharing" spec="^5.1.8" />
    <plugin name="cordova-plugin-crosswalk-webview" spec="^2.3.0">
        <variable name="XWALK_VERSION" value="23+" />
        <variable name="XWALK_LITEVERSION" value="xwalk_core_library_canary:17+" />
        <variable name="XWALK_COMMANDLINE" value="--disable-pull-to-refresh-effect" />
        <variable name="XWALK_MODE" value="embedded" />
        <variable name="XWALK_MULTIPLEAPK" value="false" />
    </plugin>
    <plugin name="cordova-android-support-gradle-release" spec="^1.4.4">
        <variable name="ANDROID_SUPPORT_VERSION" value="23.+" />
    </plugin>
    <plugin name="cordova-plugin-safariviewcontroller" spec="1.5.3" />
    <plugin name="cordova-plugin-customurlscheme" spec="^4.3.0">
        <variable name="URL_SCHEME" value="REDACTED" />
    </plugin>
    <plugin name="cordova-plugin-appcenter-analytics" spec="^0.1.5" />
    <plugin name="cordova-plugin-appcenter-crashes" spec="^0.1.5" />
</widget>
```

**Comment by mushishi78** [comment]
I tried upgrading to 1.5.4 and built the android project by manually editing the `build.gradle` file to have jack enabled:

```
    defaultConfig {
        ...
        jackOptions {
            enabled true
        }
    }
```

And instead of getting the original error of this thread:

```
Jack is required to support java 8 language features.  Either enable Jack or remove sourceCompatibility JavaVersion.VERSION_1_8.
```

I then got the new error:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':transformClassesWithPreJackPackagedLibrariesForDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
	at 
....
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
	at com.android.builder.core.AndroidBuilder.convertByteCodeUsingJackApis(AndroidBuilder.java:1812)
	at com.android.builder.core.AndroidBuilder.convertByteCodeUsingJack(AndroidBuilder.java:1643)
	at 
```

Which implies I would have got the error anyway, so I think I'll open a separate issue for this.

**Comment by ericmorand** [comment]
So you created a breaking change on a patch release?

**Comment by CookieCookson** [comment]
For people who need to downgrade their version, `1.5.3` is not published to npm so you cannot install it with `npm install cordova-plugin-safariviewcontroller@1.5.3`. However, the `1.5.3` release has been tagged on GitHub, so you can install it by doing:
```
npm install https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller#1.5.3
```

**Comment by biswas123** [comment]
Tried on android@6.3.0, with 1.5.3
`cordova plugin add cordova-plugin-safariviewcontroller@1.5.3
`
plugin installs successfully.

Added:
```
   <plugin name="cordova-android-support-gradle-release" spec="^1.4.4">
        <variable name="ANDROID_SUPPORT_VERSION" value="27.+" />
    </plugin>
```

But still Android build results to:
```
Execution failed for task ':transformClassesWithPreJackPackagedLibrariesForDebug'.
> java.lang.NullPointerException (no error message)
```

Guys, anyone can provide me with exact steps to run this on android 6.3.0 with 1.5.3 ? :(

**Comment by shawns582** [comment]
any luck with fixing this?
