### ISSUE TITLE
android: Exception when calling getInstantAppLaunchData

### ISSUE THREAD

**Issue by WuglyakBolgoink** [EddyVerbruggen/cordova-plugin-safariviewcontroller#150]
Halo guys!

Has anyone this error on closing? Actually we open web-site in tab, and site did redirect with custom-url-schema `"redirectURL": "myApp://authtoken"`. But the View will be not closed... and in logcat logs I found this error:

```
2019-08-29 13:19:08.786 13101-16768/? I/chatty: uid=10255(MY_APP_PACKAGE_NAME) pool-1-thread-8 expire 4 lines
2019-08-29 13:19:08.789 13101-16768/? E/ActivityThread: Failed to find provider info for com.teslacoilsw.notifier
2019-08-29 13:19:08.925 3709-6255/? I/ActivityManager: START u0 {act=android.intent.action.VIEW dat=https://CLIEN_PORTAL/... pkg=com.android.chrome cmp=com.android.chrome/com.google.android.apps.chrome.IntentDispatcher (has extras)} from uid 10255
2019-08-29 13:19:08.930 13101-13101/? D/CordovaActivity: Paused the activity.
2019-08-29 13:19:08.967 14705-14705/? I/cr_InstantAppsHandler: Not handling with Instant Apps (missing CUSTOM_APPS_INSTANT_APP_EXTRA)
2019-08-29 13:19:08.971 3709-4027/? I/ActivityManager: START u0 {act=android.intent.action.VIEW dat=https://CLIENT_PORTAL/... flg=0x18080000 pkg=com.android.chrome cmp=com.android.chrome/org.chromium.chrome.browser.customtabs.CustomTabActivity (has extras)} from uid 10041
2019-08-29 13:19:09.077 14705-16765/? I/cr_tabmodel: Starting to fetch tab list for tab_state405
2019-08-29 13:19:09.077 14705-16765/? I/cr_tabmodel: State file does not exist.
2019-08-29 13:19:09.158 3709-3732/? I/ActivityManager: Displayed com.android.chrome/org.chromium.chrome.browser.customtabs.CustomTabActivity: +152ms (total +215ms)
2019-08-29 13:19:09.179 14705-14705/? I/cr_ContextualSearch: Tap suppression enabled: false
2019-08-29 13:19:09.392 14705-14705/? I/cr_InstantAppsHandler: Not handling with Instant Apps (missing CUSTOM_APPS_INSTANT_APP_EXTRA)
2019-08-29 13:19:09.481 13101-13101/? D/CordovaActivity: Stopped the activity.
2019-08-29 13:19:16.420 14705-14705/? E/cr_InstantAppsHandlerI: Exception when calling getInstantAppLaunchData
    Df: 19500: Not an instant app
        at Gk.a(PG:3)
        at Gc.a(PG:7)
        at com.google.android.gms.common.api.internal.BasePendingResult.c(PG:136)
        at com.google.android.gms.common.api.internal.BasePendingResult.a(PG:97)
        at Lg.a(PG:2)
        at Lc.a(PG:29)
        at RD.onTransact(PG:12)
        at android.os.Binder.execTransact(Binder.java:697)
```

**Comment by mohit1993** [comment]
I am also facing same issue after this chrome stops working 
2021-01-13 13:04:13.492 25012-25012/? E/cr_InstantAppsHandlerI: Exception when calling getInstantAppLaunchData
    Fr: 19500: Not an instant app
        at jv.a(PG:7)
        at com.google.android.gms.common.api.internal.BasePendingResult.b(PG:32)
        at com.google.android.gms.common.api.internal.BasePendingResult.a(PG:42)
        at iA.a(PG:28)
        at LD.onTransact(PG:3)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
2021-01-13 13:04:14.803 25012-25012/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.android.chrome, PID: 25012
    java.lang.NullPointerException: Attempt to invoke interface method 'void Hc2.a(java.lang.Object)' on a null object reference
        at nn.a(PG:4)
        at YL.run(PG:8)
        at android.os.Handler.handleCallback(Handler.java:914)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:239)
        at android.app.ActivityThread.main(ActivityThread.java:7604)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
