### ISSUE TITLE
Error in Success callbackId: SafariViewController. Webview undefined in Android older than 6.0

### ISSUE THREAD

**Issue by YaroslavPr** [EddyVerbruggen/cordova-plugin-safariviewcontroller#76]
I'm trying to add Auth0 JWT authorization with google-oauth2 connection using Auth0 Cordova and SafariViewController. 

Everything works fine in Android 6.0+ but in older version I'm getting error not related to my own code:
`Error in Success callbackId: SafariViewController767894223 : TypeError: Cannot read property 'open' of undefined core.es5.js:1084 
ERROR Error: Uncaught (in promise): 
TypeError: Cannot read property 'open' of undefined
    at WebView.open (file:///android_asset/www/build/vendor.js:159671:20)
    at file:///android_asset/www/build/vendor.js:92696:11
    at file:///android_asset/www/build/vendor.js:159612:12
    at Object.cordova.callbackFromNative (file:///android_asset/www/cordova.js:293:58)
`

More details on [stackoverflow](https://stackoverflow.com/questions/45708468/cannot-open-oauth-form-in-android-versions-under-6-0-0-using-safariviewcontrolle)

**Comment by YaroslavPr** [comment]
Adding `cordova-plugin-inappbrowser` resolved the issue.
